# Generated by Django 6.1.dev20251017073113 on 2025-10-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basemodel",
            name="choice",
            field=models.CharField(
                blank=True,
                choices=[
                    ("one", "One"),
                    ("two", "Two"),
                    (
                        "three",
                        "very long long long long long long long long long long long long long long long long long long long long choice",
                    ),
                ],
                max_length=128,
                null=True,
            ),
        ),
    ]
