# Generated by Django 6.1.dev20260212163335 on 2026-02-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("form", "0002_alter_basemodel_choice"),
    ]

    operations = [
        migrations.CreateModel(
            name="HorizontalMultipleFields",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("char", models.CharField(max_length=128)),
                ("integer", models.IntegerField()),
                ("datetime", models.DateTimeField()),
                ("url", models.URLField()),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("m2m", models.ManyToManyField(blank=True, to="form.common")),
            ],
        ),
    ]
