# Generated by Django 6.0.dev20250902194005 on 2025-09-05 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomWidgetInline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("char", models.CharField(blank=True, max_length=128, null=True)),
                ("file", models.FileField(upload_to="")),
                (
                    "not_required_file",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                ("url", models.URLField()),
                ("time", models.TimeField()),
                ("date", models.DateField()),
                ("datetime", models.DateTimeField()),
                (
                    "fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inline.customwidgetinline",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ErrorInline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("char", models.CharField(max_length=128)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                (
                    "fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inline.errorinline",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FieldsetInline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("char", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "not_required_file",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                (
                    "choice",
                    models.CharField(
                        choices=[("one", "One"), ("two", "Two"), ("three", "Three")],
                        max_length=10,
                    ),
                ),
                ("datetime", models.DateTimeField()),
                (
                    "fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inline.fieldsetinline",
                    ),
                ),
                (
                    "mtom",
                    models.ManyToManyField(blank=True, to="inline.fieldsetinline"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HelpTextInline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "char",
                    models.CharField(
                        help_text="char field help text..", max_length=128
                    ),
                ),
                ("boolean", models.BooleanField(help_text="boolean field help text..")),
                ("integer", models.IntegerField(help_text="integer field help text..")),
                ("float", models.FloatField(help_text="float field help text..")),
                (
                    "datetime",
                    models.DateTimeField(help_text="datetime field help text.."),
                ),
                (
                    "fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inline.helptextinline",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Inline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("char", models.CharField(max_length=1000)),
                (
                    "fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inline.inline",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LongInline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("char", models.CharField(max_length=128)),
                ("text", models.TextField()),
                ("integer", models.IntegerField()),
                ("boolean", models.BooleanField()),
                ("email", models.EmailField(max_length=254)),
                ("decimal", models.DecimalField(decimal_places=2, max_digits=10)),
                ("float", models.FloatField()),
                (
                    "fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inline.longinline",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ManyToManyInline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("char", models.CharField(max_length=128)),
                (
                    "fk",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inline.manytomanyinline",
                    ),
                ),
                (
                    "mtom1",
                    models.ManyToManyField(blank=True, to="inline.manytomanyinline"),
                ),
                (
                    "mtom2",
                    models.ManyToManyField(blank=True, to="inline.manytomanyinline"),
                ),
                (
                    "mtom3",
                    models.ManyToManyField(blank=True, to="inline.manytomanyinline"),
                ),
            ],
        ),
    ]
