# Generated by Django 6.0.dev20250902194005 on 2025-09-05 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inline", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customwidgetinline",
            name="char",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="fieldsetinline",
            name="char",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
