# Generated by Django 6.1.dev20251106205059 on 2025-11-09 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=200)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
            ],
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice_text", models.CharField(max_length=200)),
                ("votes", models.IntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="polls.question"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuestionAdmin07",
            fields=[],
            options={
                "verbose_name": "question",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("polls.question",),
        ),
        migrations.CreateModel(
            name="QuestionAdmin08",
            fields=[],
            options={
                "verbose_name": "question",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("polls.question",),
        ),
        migrations.CreateModel(
            name="QuestionAdmin10",
            fields=[],
            options={
                "verbose_name": "question",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("polls.question",),
        ),
        migrations.CreateModel(
            name="QuestionAdmin11",
            fields=[],
            options={
                "verbose_name": "question",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("polls.question",),
        ),
        migrations.CreateModel(
            name="QuestionAdmin12",
            fields=[],
            options={
                "verbose_name": "question",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("polls.question",),
        ),
        migrations.CreateModel(
            name="QuestionAdmin13",
            fields=[],
            options={
                "verbose_name": "question",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("polls.question",),
        ),
        migrations.CreateModel(
            name="QuestionAdmin14",
            fields=[],
            options={
                "verbose_name": "question",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("polls.question",),
        ),
    ]
