# Generated by Django 6.1.dev20251207140632 on 2025-12-08 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("flatpages", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocsFlatPage",
            fields=[
                (
                    "flatpage_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="flatpages.flatpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "flat page",
                "verbose_name_plural": "flat pages",
            },
            bases=("flatpages.flatpage",),
        ),
    ]
