# Generated by Django 6.1.dev20260212163335 on 2026-02-19 10:12

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserForScreenshotActions",
            fields=[],
            options={
                "verbose_name": "user",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("users.userforscreenshot",),
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
