# Generated by Django 6.1.dev20251017073113 on 2025-10-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("changelist", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basemodel",
            name="boolean",
            field=models.BooleanField(
                default=False,
                verbose_name="very long long long long long long long longlong long long verbose name.",
            ),
        ),
    ]
