# Generated by Django 6.1.dev20260220014727 on 2026-02-20 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("changelist", "0002_alter_basemodel_boolean"),
    ]

    operations = [
        migrations.AlterField(
            model_name="forfkfield",
            name="fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="changelist.forfk2field",
            ),
        ),
    ]
